name: plantation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    - images\plant.jpg
    - images\image2.jpg
    - images\imag4.png
    - images\s-image3.png
    - images\Group 5471.png
    - images\Group 5472@2x.png
    - images\Group 5473.png
    - images\image22-removebg-preview.png
    - images\image33-removebg-preview.png
    - images\Selset-Small-Green--removebg-preview.png
    - images\mini_rubber_plant-removebg-preview.png
     
    
